site_name: pythonvideoannotator Models GUI
site_url: https://pythonvideoannotator-models-gui.readthedocs.io/
site_description: GUI Models of the Python Video Annotator
site_author: Champalimaud Foundation

repo_url: https://bitbucket.org/fchampalimaud/pythonvideoannotator-models-gui

pages:
- Home: 'index.md'
- Models: 
  - 'Project': 'models/project.md'
  - 'video.Video': 'models/video.md'
  - 'video.objects.Object2d': 'models/object2d.md'
  - 'video.objects.object2d.datasets.Path': 'models/path.md'

copyright: Copyright &copy; 2016 <a href="/release-notes/">Champalimaud Foundation</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Scientific Software Platform</a>.
